sudo: required
services:
  - docker

before_install:
  - docker build -t 7676ee/docker-basic-nginx -f Dockerfile.dev .

script:
  - docker run 7676ee/docker-basic-nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-basic-nginx"
  env: "DockerBasicNginx-env"
  bucket_name: "elasticbeanstalk-us-east-2-421718756082"
  bucket_path: "docker-basic-nginx"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"